# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 14
      - name: setting testing environment 
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo systemctl start mongod
      - name: Build with Maven
        run: mvn -B clean:clean compiler:compile source:jar assembly:single --file pom.xml
      - uses: "marvinpinto/action-automatic-releases@v1.0.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            /home/runner/work/Model-based-Framework-for-Developing-Multi-Database-Application/Model-based-Framework-for-Developing-Multi-Database-Application/LICENSE.txt
            /home/runner/work/Model-based-Framework-for-Developing-Multi-Database-Application/Model-based-Framework-for-Developing-Multi-Database-Application/target/*.jar
