# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 14
        uses: actions/setup-java@v3.5.0
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn -B clean:clean compiler:compile source:jar assembly:single --file pom.xml
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            /home/runner/work/Model-based-Framework-for-Developing-Multi-Database-Application/Model-based-Framework-for-Developing-Multi-Database-Application/LICENSE.txt
            /home/runner/work/Model-based-Framework-for-Developing-Multi-Database-Application/Model-based-Framework-for-Developing-Multi-Database-Application/target/*.jar
